STATUS = 'status'
TAGS = 'tags'
DESCRIPTION = 'description'
BACKLOG = 'backlog'
UPCOMING = 'upcoming'
WIP = 'wip'
BLOCKED = 'blocked'
DONE = 'done'
TITLE = 'title'
ID = 'id'
CREATED = 'created'
DATE_FORMAT = '%y-%m-%d %H:%M:%S'
USER_DATE_FORMATS = []
INDENT = 2
